const data = [
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    },
    {
        full_name: "Uniswap", 
        description : "We build state of the art open source apps to access the Uniswap protocol and contribute to the world of decentralized finance.", 
        date_founded: new Date("2012-12-19"), 
        date_created: new Date("2012-12-19"),
        logo_link: "https://daolist.fyi/_next/image?url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg&w=64&q=75", 
        category: "Protocol", 
        governance_token_name: "Uniswap",
        governance_token_symbol: "UNI", 
        dao_structure: "gov_token", 
        voting_process: "UNI tokens represent voting shares in Uniswap governance. You can vote on each proposal yourself or delegate your votes to a third party.",
        TVL: 28309879, 
        tech_stack: "Uniswap is actively using 21 technologies for its website, according to BuiltWith. These include Viewport Meta, IPhone / Mobile Compatible, and LetsEncrypt.",
        notes: "String", 
        blockchain: "Ethereum", 
        headquarters: "Here",
        "AUM": 76987686,
        "numTwitterFollowers":23523532,
        website_link: "https://uniswap.org/"
    }
]

module.exports = data